name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install concurrently
      run: npm install concurrently
    - name: Install Flask
      run: pip install flask
    - name: Install Datasets
      run: pip install datasets
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Allure
      run: npm i -D @playwright/test allure-playwright
    - name: Install Allure command line
      run: npm i -D allure-commandline
    - name: Start server
      run: npm run app
    - name: Run Playwright tests and create Allure report data
      run: npm run tests
    - name: Add Allure to PATH
      run: export PATH="$PATH:./node_modules/.bin"
    - name: Generate Allure report data
      run: npm run generate-allure
    - name: Serve the Allure report
      run: npm run serve-allure
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
      
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.MYTOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
